/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea el CV de un usuario */
        post: operations["ResumeController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateWorkExperienceDto: {
            companyName: string;
            position: string;
            startDate: string;
            endDate?: string;
            isCurrent?: boolean;
            description?: string;
        };
        CreateEducationDto: {
            institution: string;
            degree: string;
            fieldOfStudy?: string;
            startDate: string;
            endDate?: string;
        };
        CreateResumeSkillDto: {
            name: string;
            proficiencyLevel?: number;
        };
        CreateResumeDto: {
            /** Format: uuid */
            userId: string;
            title: string;
            summary?: string;
            workExperiences?: components["schemas"]["CreateWorkExperienceDto"][];
            education?: components["schemas"]["CreateEducationDto"][];
            skills?: components["schemas"]["CreateResumeSkillDto"][];
        };
        WorkExperienceResponseDto: {
            id: string;
            companyName: string;
            position: string;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string | null;
            isCurrent: boolean;
            description: string | null;
        };
        EducationResponseDto: {
            id: string;
            institution: string;
            degree: string;
            fieldOfStudy: string | null;
            /** Format: date-time */
            startDate: string;
            /** Format: date-time */
            endDate: string | null;
        };
        ResumeSkillResponseDto: {
            skillId: string;
            name: string;
            proficiencyLevel: number | null;
        };
        ResumeResponseDto: {
            id: string;
            userId: string;
            title: string;
            summary: string | null;
            workExperiences: components["schemas"]["WorkExperienceResponseDto"][];
            education: components["schemas"]["EducationResponseDto"][];
            skills: components["schemas"]["ResumeSkillResponseDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ResumeController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResumeDto"];
            };
        };
        responses: {
            /** @description CV creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponseDto"];
                };
            };
            /** @description El usuario ya tiene un CV */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
